# Generated by Django 5.2.1 on 2025-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Пароль в открытом виде (только для администраторов)', max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
