# Generated by Django 5.2.1 on 2025-09-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("users", "0003_employee_plain_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="accessible_stores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Магазины, к которым сотрудник имеет доступ",
                related_name="accessible_employees",
                to="stores.store",
                verbose_name="Доступные магазины",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="store",
            field=models.ForeignKey(
                default=1,
                help_text="Магазин, к которому привязан сотрудник",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="stores.store",
                verbose_name="Магазин",
            ),
            preserve_default=False,
        ),
    ]
