# Generated by Django 5.2.1 on 2025-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("users", "0005_alter_employee_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="accessible_stores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Магазины, к которым сотрудник имеет доступ",
                null=True,
                related_name="accessible_employees",
                to="stores.store",
                verbose_name="Доступные магазины",
            ),
        ),
    ]
