# Generated by Django 5.2.1 on 2025-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_employee_accessible_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="store",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
