# Generated by Django 5.2.1 on 2025-09-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("users", "0007_alter_employee_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Магазин, к которому привязан сотрудник",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="stores.store",
                verbose_name="Магазин",
            ),
        ),
    ]
