# Generated by Django 5.2.1 on 2025-09-04 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма покупок",
                    ),
                ),
                (
                    "transaction_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество транзакций"
                    ),
                ),
                (
                    "debt_added",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Добавлено долга",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="customers.customer",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика клиента",
                "verbose_name_plural": "Аналитика клиентов",
                "ordering": ["-date"],
                "unique_together": {("customer", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Продано единиц"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Выручка",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="inventory.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика товара",
                "verbose_name_plural": "Аналитика товаров",
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Общая сумма продаж",
                    ),
                ),
                (
                    "total_transactions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество транзакций"
                    ),
                ),
                (
                    "total_items_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество проданных товаров"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("transfer", "Перевод"),
                            ("card", "Карта"),
                            ("debt", "В долг"),
                        ],
                        max_length=20,
                        verbose_name="Метод оплаты",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кассир",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="stores.store",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сводка по продажам",
                "verbose_name_plural": "Сводки по продажам",
                "ordering": ["-date"],
                "unique_together": {("store", "date", "payment_method")},
            },
        ),
    ]
