# Generated by Django 5.2.1 on 2025-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salessummary",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод"),
                    ("card", "Карта"),
                    ("debt", "В долг"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salessummary",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salessummary",
            name="total_items_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salessummary",
            name="total_transactions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
