# Generated by Django 5.2.1 on 2025-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="unique_category_per_store"
            ),
        ),
    ]
