# Generated by Django 5.2.1 on 2025-08-08 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbatch",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.sizeinfo",
                verbose_name="Размер",
            ),
        ),
    ]
