# Generated by Django 5.2.1 on 2025-09-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_productcategory_unique_together_and_more"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sizeinfo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sizeinfo",
            name="store",
            field=models.ForeignKey(
                default="91fb5aee-7677-433e-aa42-9d800536a55d",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="stores.store",
                verbose_name="Магазин",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="sizeinfo",
            constraint=models.UniqueConstraint(
                fields=("store", "size"), name="unique_size_per_store"
            ),
        ),
    ]
