# Generated by Django 5.2.1 on 2025-09-10 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_sizeinfo_unique_together_sizeinfo_store_and_more"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Мягкое удаление - товар скрыт, но сохранен для истории",
                verbose_name="Удален",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_deleted"], name="inventory_p_is_dele_1f66ff_idx"
            ),
        ),
    ]
