# Generated by Django 5.2.1 on 2025-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_deleted_at_product_is_deleted_and_more"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productcategory",
            name="unique_category_per_store",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("store", "name"),
                name="unique_active_category_per_store",
            ),
        ),
    ]
