# Generated by Django 5.2.1 on 2025-07-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_unitofmeasure_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('allow_fraction', models.BooleanField(default=False)),
                ('base_unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Коэффициент к базовой единице', max_digits=10),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.measurementcategory'),
            preserve_default=False,
        ),
    ]
