# Generated by Django 5.2.1 on 2025-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_productcategory_unique_category_per_store_and_more"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sizeinfo",
            name="unique_size_per_store",
        ),
        migrations.AddField(
            model_name="sizeinfo",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddConstraint(
            model_name="sizeinfo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("store", "size"),
                name="unique_active_size_per_store",
            ),
        ),
    ]
