# Generated by Django 5.2.1 on 2025-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_purchase_date",
            field=models.DateTimeField(
                blank=True, help_text="Дата последней покупки", null=True
            ),
        ),
    ]
