# Generated by Django 5.2.1 on 2025-07-26 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_debt_alter_customer_email_and_more'),
        ('sales', '0002_alter_transaction_payment_method_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
        migrations.AddField(
            model_name='customer',
            name='debts_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество транзакций с долгом'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего потрачено'),
        ),
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма долга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='customers.customer', verbose_name='Покупатель')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='sales.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Долг покупателя',
                'verbose_name_plural': 'Долги покупателей',
                'ordering': ['-created_at'],
            },
        ),
    ]
